name: PBTools_dev
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - jupyter
  - numpy
  - pandas
  - mdanalysis
  - networkx
  - pycodestyle
  - pydocstyle
  - pylint
  - pytest
  - setuptools
  - sphinx
  - spyder
  - pip:
    - pbxplore

