name: PBTools_doc
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - numpy
  - pandas
  - mdanalysis
  - pytest
  - sphinx
  - sphinx_rtd_theme
  - pip:
    - pbxplore
    - nbsphinx-link
    - recommonmark

